---
- name: Prepare
  hosts: all
  tasks:
    - name: Ensure destination directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /usr/local/bin
        - /opt/hello
