---
- name: Download and install assets (linux)
  when: ansible_os_family != 'Windows'
  ansible.builtin.include_tasks: install_linux.yml
  loop: "{{ _ejecto_releaseo_downloads }}"
  loop_control:
    loop_var: _ejecto_item

- name: Download and install assets (windows)
  when: ansible_os_family == 'Windows'
  ansible.builtin.include_tasks: install_windows.yml
  loop: "{{ _ejecto_releaseo_downloads }}"
  loop_control:
    loop_var: _ejecto_item
